name: Clean Branch
on: [delete]
jobs:
  clean-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Github Branch
        id: get-branch
        run: echo ::set-output name=branch::$(echo ${{ github.event.ref }} | sed "s/_/-/g" | sed "s/\//-/g" | sed "s/ /-/g")

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1

      - id: get-lightsail-ip-address
        name: Get Lightsail Instance IP Address
        run: echo ::set-output name=IP_ADDRESS::$(aws lightsail get-instance-access-details --instance-name project-lab-${{ steps.get-branch.outputs.branch }} | jq -r '.accessDetails.ipAddress')

      - name: Destroy lightsail
        uses: dflook/terraform-destroy@v1
        with:
          path: "terraform/lightsail/"
          workspace: ${{ steps.get-branch.outputs.branch }}
        continue-on-error: true

      - name: Destroy Distribution
        uses: dflook/terraform-destroy@v1
        with:
          path: "terraform/distribution/"
          workspace: ${{ steps.get-branch.outputs.branch }}
          var: lightsail_instance_ip_address=${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
        continue-on-error: true
