name: Automatic Clean Branch
on: [delete]
jobs:
  get-github-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Branch
        id: get-branch
        run: echo ::set-output name=branch::$(echo ${{ github.event.ref }} | sed "s/_/-/g" | sed "s/\//-/g" | sed "s/ /-/g")
    outputs:
      branch_name: ${{ steps.get-branch.outputs.branch }}

  clean-branch:
    needs: get-github-branch
    uses: ./.github/workflows/run-clean.yml
    with:
      branch_name: ${{ needs.get-github-branch.outputs.branch_name }}
    secrets: inherit
