name: Deploy Production
on:
  push:
    tags:
      - "*"
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    uses: ./.github/workflows/run-deploy.yml
    with:
      branch_name: production
      github_ref: ${{ github.ref }}
      AWS_SECRET_NAME: env-production
    secrets: inherit
