name: Deploy Branch
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Branch
        id: get-branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/*/} | sed "s/_/-/g" | sed "s/\//-/g" | sed "s/ /-/g" | tr '[:upper:]' '[:lower:]')
      - name: Dispatch Deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPACTH_ACCESS_TOKEN }}
          repository: wizeline/project-lab
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}", "branch": "${{ steps.get-branch.outputs.branch }}" , "secret_name":"env-development" }'
