name: Deploy Branch
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  get-github-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Branch
        id: get-branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/*/} | sed "s/_/-/g" | sed "s/\//-/g" | sed "s/ /-/g" | tr '[:upper:]' '[:lower:]')
    outputs:
      branch_name: ${{ steps.get-branch.outputs.branch }}

  deploy-branch:
    needs: get-github-branch
    uses: ./.github/workflows/run-deploy.yaml
    with:
      branch_name: ${{ needs.get-github-branch.outputs.branch-name }}
      github_ref: ${{ github.ref_name }}
      AWS_SECRET_NAME: env-development
    secrets: inherit
