name: Deploy Development
on:
  push:
    branches: [main]
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    uses: ./.github/workflows/run-deploy.yml
    with:
      branch_name: development
      github_ref: ${{ github.ref_name }}
      AWS_SECRET_NAME: env-development
    secrets: inherit
