name: Deploy Production
on:
  push:
    tags:
      - "*"
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    uses: ./.github/workflows/run-deploy.yaml
    with:
      branch_name: production
      github_ref: ${{ github.ref }}
    secrets:
      AWS_SECRET_NAME: env-production
      PIPELINE_AWS_ACCESS_KEY_ID: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
      PIPELINE_AWS_SECRET_ACCESS_KEY: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
