name: Deploy Rollback
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag which should be deployed"
        required: true
        default: ""
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    uses: ./.github/workflows/run-deploy.yml
    with:
      branch_name: production
      github_ref: ${{ github.event.inputs.tag }}
      AWS_SECRET_NAME: env-production
    secrets: inherit
