name: Deploy Production
on:
  push:
    tags:
      - "v*.*.*"
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPACTH_ACCESS_TOKEN }}
          repository: wizeline/project-lab
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}", "branch": "default" , "secret_name":"env-production","update_tag":"yes"}'
