name: Clean Branch
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
    secrets:
      PIPELINE_AWS_ACCESS_KEY_ID:
        required: true
      PIPELINE_AWS_SECRET_ACCESS_KEY:
        required: true
defaults:
  run:
    shell: bash
jobs:
  clean-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1

      - id: get-lightsail-ip-address
        name: Get Lightsail Instance IP Address
        run: echo ::set-output name=IP_ADDRESS::$(aws lightsail get-instance-access-details --instance-name project-lab-${{ inputs.branch_name }} | jq -r '.accessDetails.ipAddress')

      - name: Destroy lightsail
        uses: dflook/terraform-destroy@v1
        with:
          path: "terraform/lightsail/"
          workspace: ${{ inputs.branch_name }}
        continue-on-error: true

      - name: Destroy Distribution
        uses: dflook/terraform-destroy@v1
        with:
          path: "terraform/distribution/"
          workspace: ${{ inputs.branch_name }}
          var: lightsail_instance_ip_address=${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
        continue-on-error: true
