name: Run Deploy
on:
  repository_dispatch:
    types: [deploy]
defaults:
  run:
    shell: bash
jobs:
  deploy-branch:
    env:
      NODE_ENV: "production"
      DB_PATH: "/home/admin/projectlab/db/db.sqlite"
      ADD_SEED_DATA: "yes"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1

      - name: Get Github Branch
        id: get-branch
        run: echo ::set-output name=branch::$(echo "${{ github.event.client_payload.branch }}")

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Remove existing .env file
        run: rm -rf .env

      - name: Set .env File
        run: |
          aws secretsmanager get-secret-value --secret-id env-${{ steps.get-branch.outputs.branch }} | jq -r '.SecretString' | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" > env-tmp
          cp env-tmp .env

      - name: Install Blitz Globally
        run: yarn global add blitz

      - name: Install Dependancies
        run: yarn install

      - name: Create DB Folder
        run: sudo mkdir -p /home/admin/projectlab/db

      - name: Set Up App Domain
        run: |
          if [ "${{ steps.get-branch.outputs.branch }}" == "production" ]; then
            sed -i -e "s/http:\/\/localhost:3000/https:\/\/labs.wizeline.com/g" ./blitz.config.ts
          else
            sed -i -e "s/http:\/\/localhost:3000/https:\/\/${{ steps.get-branch.outputs.branch }}.labs.wizeline.com/g" ./blitz.config.ts
          fi

      - name: Install Litestream
        if: ${{ steps.get-branch.outputs.branch == 'default' }}
        run: |
          wget https://github.com/benbjohnson/litestream/releases/download/v0.3.5/litestream-v0.3.5-linux-amd64.deb
          sudo dpkg -i litestream-v0.3.5-linux-amd64.deb
          litestream version

      - name: Restore Database
        if: ${{ steps.get-branch.outputs.branch == 'default' }}
        run: litestream restore -o ${{ env.DB_PATH }} "s3://${{ secrets.LITESTREAM_S3_BUCKET }}/${{ secrets.LITESTREAM_S3_PATH }}"
        continue-on-error: true

      - name: Init DB
        run: |
          if [ -f "${{ env.DB_PATH }}" ]; then
            blitz prisma migrate deploy
          else
            blitz prisma migrate reset --force
          fi

      - name: Add Full Text Searches
        run: sqlite3 ${{ env.DB_PATH }} < db/search_indexes.sql

      - name: Sync Skills With Wizeline OS
        run: yarn sync-all-from-wos

      - name: Add Test Data
        run: |
          if [ "${{ env.ADD_SEED_DATA }}" == "yes" ]; then
            blitz db seed
          fi

      - name: Terraform Change Workspace Lightsail
        uses: dflook/terraform-new-workspace@v1
        with:
          path: "terraform/lightsail/"
          workspace: ${{ steps.get-branch.outputs.branch }}

      - name: Terraform Apply Lightsail
        uses: dflook/terraform-apply@v1
        with:
          path: "terraform/lightsail/"
          workspace: ${{ steps.get-branch.outputs.branch }}
          auto_approve: true

      - id: get-lightsail-username
        name: Get Lightsail Instance Username
        run: echo ::set-output name=USERNAME::$(aws lightsail get-instance-access-details --instance-name project-lab-${{ steps.get-branch.outputs.branch }} | jq -r '.accessDetails.username')

      - id: get-lightsail-ip-address
        name: Get Lightsail Instance IP Address
        run: echo ::set-output name=IP_ADDRESS::$(aws lightsail get-instance-access-details --instance-name project-lab-${{ steps.get-branch.outputs.branch }} | jq -r '.accessDetails.ipAddress')

      - name: Prepare Server For Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
          username: ${{steps.get-lightsail-username.outputs.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/projectlab/tmp
            mkdir -p ~/projectlab/app
            mkdir -p ~/projectlab/db
            mkdir -p ~/projectlab/tmp

      - name: Remove Node Modules
        run: rm -rf node_modules

      - name: Move DB
        run: mv ${{ env.DB_PATH }} ./db/db.sqlite

      - name: Copy Files To Lightsail Instance
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{steps.get-lightsail-username.outputs.USERNAME}}
          server: ${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./*"
          remote_path: "/home/admin/projectlab/tmp/"
          args: "-o ConnectTimeout=60"

      - name: Configure Server
        uses: appleboy/ssh-action@master
        with:
          timeout: 60s
          command_timeout: 30m
          host: ${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
          username: ${{steps.get-lightsail-username.outputs.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/admin/projectlab/tmp/scripts/setup.sh
            /home/admin/projectlab/tmp/scripts/setup.sh ${{ steps.get-branch.outputs.branch }} ${{ secrets.LITESTREAM_AWS_ACCESS_KEY_ID }} ${{ secrets.LITESTREAM_AWS_SECRET_ACCESS_KEY }}
            rm -rf ~/projectlab/tmp

      - name: Terraform Change Workspace Distribution
        uses: dflook/terraform-new-workspace@v1
        with:
          path: "terraform/distribution/"
          workspace: ${{ steps.get-branch.outputs.branch }}

      - name: Terraform Apply Distribution
        uses: dflook/terraform-apply@v1
        with:
          path: "terraform/distribution/"
          workspace: ${{ steps.get-branch.outputs.branch }}
          auto_approve: true
          var: lightsail_instance_ip_address=${{steps.get-lightsail-ip-address.outputs.IP_ADDRESS}}
