name: Run Tests
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    timeout-minutes: 30
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1
      - name: Remove existing .env file
        run: rm -rf .env

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "12"
          postgresql db: lab_test
          postgresql user: lab_user
          postgresql password: lab_pass

      - name: Set .env File
        run: echo 'PG_URL=postgresql://lab_user:lab_pass@localhost/lab_test' > .env
      - name: Set double .env File (bug in prisma)
        run: echo 'DATABASE_URL=postgresql://lab_user:lab_pass@localhost/lab_test' >> .env

      - name: Install Dependancies
        run: yarn install

      - name: Init DB
        run: npx blitz prisma migrate reset --force

      - name: Run Tests
        run: yarn test
        env:
          NODE_ENV: test

      - name: Add Test Data
        run: npx blitz db seed

      - name: Run Build
        run: yarn build
